env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: '1'
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  run_tests_windows:
    if: github.event_name != 'workflow_dispatch'
    runs-on: windows-latest
    steps:
      - name: steps::checkout_repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          clean: false
      - name: steps::setup_cargo_config
        run: |
          New-Item -ItemType Directory -Path "./../.cargo" -Force
          Copy-Item -Path "./.cargo/ci-config.toml" -Destination "./../.cargo/config.toml"
        shell: pwsh
      - name: steps::clear_target_dir_if_large
        run: ./script/clear-target-dir-if-larger-than.ps1 350 200
        shell: pwsh

      - uses: dtolnay/rust-toolchain@stable
      #  with:
      #    components: clippy  #rustfmt, 
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ github.repository }}-${{ github.workflow }}
          cache-workspace-crates: true

      - name: steps::cargo_nextest
        run: cargo test --workspace  ##cargo nextest run --workspace --no-tests=warn  #  --no-fail-fast
        shell: pwsh
      - name: steps::cleanup_cargo_config
        if: always()
        run: |
          Remove-Item -Recurse -Path "./../.cargo" -Force -ErrorAction SilentlyContinue
        shell: pwsh
    timeout-minutes: 120
  clippy_windows:
    runs-on: windows-latest
    steps:
      - name: steps::checkout_repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          clean: false
      - name: steps::setup_cargo_config
        run: |
          New-Item -ItemType Directory -Path "./../.cargo" -Force
          Copy-Item -Path "./.cargo/ci-config.toml" -Destination "./../.cargo/config.toml"
        shell: pwsh

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy  #rustfmt, 
      #- uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ github.repository }}-${{ github.workflow }}
          cache-workspace-crates: true

      - name: steps::clippy
        run: ./script/clippy.ps1
        shell: pwsh
    timeout-minutes: 60
  bundle_windows_x86_64:
    needs:
    #- run_tests_windows
    #- clippy_windows
    runs-on: windows-latest
    env:
      CARGO_INCREMENTAL: 0
      ZED_CLIENT_CHECKSUM_SEED: ${{ secrets.ZED_CLIENT_CHECKSUM_SEED }}
      ZED_MINIDUMP_ENDPOINT: ${{ secrets.ZED_SENTRY_MINIDUMP_ENDPOINT }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_SIGNING_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_SIGNING_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_SIGNING_CLIENT_SECRET }}
      ACCOUNT_NAME: ${{ vars.AZURE_SIGNING_ACCOUNT_NAME }}
      CERT_PROFILE_NAME: ${{ vars.AZURE_SIGNING_CERT_PROFILE_NAME }}
      ENDPOINT: ${{ vars.AZURE_SIGNING_ENDPOINT }}
      FILE_DIGEST: SHA256
      TIMESTAMP_DIGEST: SHA256
      TIMESTAMP_SERVER: http://timestamp.acs.microsoft.com
    steps:
      - name: steps::checkout_repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
        with:
          clean: false

      #- uses: dtolnay/rust-toolchain@stable
      #  with:
      #    components: clippy  #rustfmt, 
      #- uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ github.repository }}-${{ github.workflow }}
          cache-workspace-crates: true

      - name: steps::clear_target_dir_if_large
        run: ./script/clear-target-dir-if-larger-than.ps1 350 200
        shell: pwsh
      - name: run_bundling::bundle_windows::bundle_windows
        run: script/bundle-windows.ps1 -Architecture x86_64
        shell: pwsh
        working-directory: ${{ env.ZED_WORKSPACE }}
      - name: run_bundling::upload_artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: Zed-x86_64.exe
          path: target/Zed-x86_64.exe
          if-no-files-found: error
      - name: run_bundling::upload_artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: zed-remote-server-windows-x86_64.zip
          path: target/zed-remote-server-windows-x86_64.zip
          if-no-files-found: error
    timeout-minutes: 120
  upload_release_assets:
    needs:
    - bundle_windows_x86_64
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
    - name: release::download_workflow_artifacts
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
      with:
        path: ./artifacts/
    - name: ls -lR ./artifacts
      run: ls -lR ./artifacts
    - name: release::prep_release_artifacts
      run: |-
        mkdir -p release-artifacts/

        mv ./artifacts/Zed-x86_64.exe/Zed-x86_64.exe release-artifacts/Zed-x86_64.exe
        mv ./artifacts/zed-remote-server-windows-x86_64.zip/zed-remote-server-windows-x86_64.zip release-artifacts/zed-remote-server-windows-x86_64.zip
    - name: gh release upload "$GITHUB_REF_NAME" --repo=zed-industries/zed release-artifacts/*
      run: gh release upload "$GITHUB_REF_NAME" --repo=zed-industries/zed release-artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'main' && github.sha || 'anysha' }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash -euxo pipefail {0}
